### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by SuperAlecs** [imjack/Factions-For-Nukkit#12]
It cause crash to the server
13:18:19 [CRITICAL] "Could not pass event 'cn.nukkit.event.player.PlayerRespawnEvent' to 'Factions v1.6.9.5': null on com.massivecraft.factions.listeners.FactionsPlayerListener
13:18:19 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.Player.doFirstSpawn(Player.java:766)
        at cn.nukkit.Player.sendNextChunk(Player.java:741)
        at cn.nukkit.Player.checkNetwork(Player.java:1613)
        at cn.nukkit.Server.tick(Server.java:1002)
        at cn.nukkit.Server.tickProcessor(Server.java:791)
        at cn.nukkit.Server.start(Server.java:770)
        at cn.nukkit.Server.<init>(Server.java:461)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.NoSuchMethodError: cn.nukkit.Player.getHealth()I
        at com.massivecraft.factions.FPlayer.updatePower(FPlayer.java:475)
        at com.massivecraft.factions.FPlayer.getPower(FPlayer.java:431)
        at com.massivecraft.factions.listeners.FactionsPlayerListener.onPlayerRespawn(FactionsPlayerListener.java:396)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 10 more

**Comment by SuperAlecs** [comment]
sorry this cause crash, when you attempt to claim a land, please fix it is urgent!

2017-1-29 14:13:18 [CRITICAL] "Could not pass event 'cn.nukkit.event.player.PlayerCommandPreprocessEvent' to 'Factions v1.6.9.6': null on com.massivecraft.factions.zcore.MPluginSecretPlayerListener
2017-1-29 14:13:18 [ALERT] cn.nukkit.utils.EventException
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
	at cn.nukkit.Player.handleDataPacket(Player.java:2898)
	at cn.nukkit.network.Network.processPackets(Network.java:185)
	at cn.nukkit.network.Network.processBatch(Network.java:156)
	at cn.nukkit.Player.handleDataPacket(Player.java:1883)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:988)
	at cn.nukkit.Server.tickProcessor(Server.java:791)
	at cn.nukkit.Server.start(Server.java:770)
	at cn.nukkit.Server.<init>(Server.java:461)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.NoSuchMethodError: cn.nukkit.Player.getHealth()I
	at com.massivecraft.factions.FPlayer.updatePower(FPlayer.java:476)
	at com.massivecraft.factions.FPlayer.getPower(FPlayer.java:432)
	at com.massivecraft.factions.Faction.getPower(Faction.java:305)
	at com.massivecraft.factions.Faction.getPowerRounded(Faction.java:329)
	at com.massivecraft.factions.FPlayer.canClaimForFactionAtLocation(FPlayer.java:630)
	at com.massivecraft.factions.FPlayer.attemptClaim(FPlayer.java:676)
	at com.massivecraft.factions.cmd.CmdClaim.perform(CmdClaim.java:42)
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:111)
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:46)
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:101)
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:46)
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:115)
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:213)
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:181)
	at com.massivecraft.factions.P.handleCommand(P.java:156)
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:223)
	at com.massivecraft.factions.zcore.MPluginSecretPlayerListener.onPlayerCommandPreprocess(MPluginSecretPlayerListener.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
	... 15 more

2017-1-29 14:13:18 [EMERGENCY] Exception happened while ticking server
2017-1-29 14:13:18 [ALERT] java.lang.NoSuchMethodError: cn.nukkit.Player.getHealth()I
	at com.massivecraft.factions.FPlayer.updatePower(FPlayer.java:476)
	at com.massivecraft.factions.FPlayer.getPower(FPlayer.java:432)
	at com.massivecraft.factions.Faction.getPower(Faction.java:305)
	at com.massivecraft.factions.Faction.getPowerRounded(Faction.java:329)
	at com.massivecraft.factions.FPlayer.canClaimForFactionAtLocation(FPlayer.java:630)
	at com.massivecraft.factions.FPlayer.attemptClaim(FPlayer.java:676)
	at com.massivecraft.factions.cmd.CmdClaim.perform(CmdClaim.java:42)
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:111)
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:46)
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:101)
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:46)
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:115)
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:213)
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:181)
	at com.massivecraft.factions.P.handleCommand(P.java:156)
	at com.massivecraft.factions.P.onCommand(P.java:166)
	at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
	at cn.nukkit.Server.dispatchCommand(Server.java:635)
	at cn.nukkit.Player.handleDataPacket(Player.java:2904)
	at cn.nukkit.network.Network.processPackets(Network.java:185)
	at cn.nukkit.network.Network.processBatch(Network.java:156)
	at cn.nukkit.Player.handleDataPacket(Player.java:1883)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:154)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:988)
	at cn.nukkit.Server.tickProcessor(Server.java:791)
	at cn.nukkit.Server.start(Server.java:770)
	at cn.nukkit.Server.<init>(Server.java:461)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by ghost** [comment]
Still an issue from what I can see, has this plugin been left to die?
