### ISSUE TITLE
I know your plugin is perfect, but....

### ISSUE THREAD

**Issue by Adam1609** [imjack/Factions-For-Nukkit#3]
2016-9-1 08:45:58 [CRITICAL] "Could not pass event 'cn.nukkit.event.entity.EntityCombustByBlockEvent' to 'Factions v1.6.9.5': null on com.massivecraft.factions.listeners.FactionsEntityListener
2016-9-1 08:45:58 [ALERT] cn.nukkit.utils.EventException
    at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
    at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
    at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:561)
    at cn.nukkit.block.BlockLava.onEntityCollide(BlockLava.java:55)
    at cn.nukkit.Player.checkBlockCollision(Player.java:1104)
    at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:838)
    at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:185)
    at cn.nukkit.Player.onUpdate(Player.java:1419)
    at cn.nukkit.level.Level.doTick(Level.java:694)
    at cn.nukkit.Server.checkTickUpdates(Server.java:920)
    at cn.nukkit.Server.tick(Server.java:994)
    at cn.nukkit.Server.tickProcessor(Server.java:785)
    at cn.nukkit.Server.start(Server.java:765)
    at cn.nukkit.Server.<init>(Server.java:456)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@5da41d02
    at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:25)
    ... 14 more

**Comment by imjack** [comment]
It's far from perfect. When I'm home I'll fix it. Which is a while away.

**Comment by Adam1609** [comment]
Could you do the tick event like in PC like, when I move to faction, it broadcast where I am in the wilderness
