### ISSUE TITLE
Bugg...

### ISSUE THREAD

**Issue by ghost** [imjack/Factions-For-Nukkit#5]
@imjack 

18:57:14 [CRITICAL] Exception while invoking run
java.lang.NullPointerException
        at cn.nukkit.Server.getPlayerExact(Server.java:1449)
        at com.massivecraft.factions.zcore.persist.PlayerEntity.getPlayer(PlayerEntity.java:10)
        at com.massivecraft.factions.zcore.persist.PlayerEntity.isOnline(PlayerEntity.java:14)
        at com.massivecraft.factions.zcore.persist.PlayerEntity.isOffline(PlayerEntity.java:24)
        at com.massivecraft.factions.FPlayer.updatePower(FPlayer.java:465)
        at com.massivecraft.factions.FPlayer.getPower(FPlayer.java:432)
        at com.massivecraft.factions.FPlayer.getPowerRounded(FPlayer.java:453)
        at com.massivecraft.factions.FPlayer.shouldBeSaved(FPlayer.java:708)
        at com.massivecraft.factions.zcore.persist.EntityCollection.saveToDisc(EntityCollection.java:183)
        at com.massivecraft.factions.zcore.persist.EM.saveAllToDisc(EM.java:52)
        at com.massivecraft.factions.zcore.persist.SaveTask.run(SaveTask.java:18)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:204)
        at cn.nukkit.Server.tick(Server.java:997)
        at cn.nukkit.Server.tickProcessor(Server.java:786)
        at cn.nukkit.Server.start(Server.java:765)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by ghost** [comment]
This reset all factions..
